apiVersion: v1
kind: Service
metadata:
  name: svc-{{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.coursesPortValue }}
      targetPort: http
      protocol: TCP
      name: {{ .Values.service.coursesPortValue }}
  selector:
    app: {{ .Release.Name }}